import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "./footer/page";
import Header from "./nav/page";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Governor Initiative",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Page Wrapper to ensure full height */}
        <div className="flex flex-col min-h-screen">
          {/* Header */}
          <Header />

          {/* Main content that takes up remaining space */}
          <main className="flex-grow">
            {children}
          </main>

          {/* Footer always at the bottom */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
